// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADLjVe5j0tylW3phBlGaW9vm4-LiS4HDQ',
    appId: '1:413064755970:web:c0a0b85e7b7decca35201b',
    messagingSenderId: '413064755970',
    projectId: 'abhimanyu-herbal-juice-6fa8e',
    authDomain: 'abhimanyu-herbal-juice-6fa8e.firebaseapp.com',
    storageBucket: 'abhimanyu-herbal-juice-6fa8e.firebasestorage.app',
    measurementId: 'G-B2NY0GSW3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwxeDh82249SZ7dtE6YWHwTwiJmTECARA',
    appId: '1:413064755970:android:6b828f06601f4afa35201b',
    messagingSenderId: '413064755970',
    projectId: 'abhimanyu-herbal-juice-6fa8e',
    storageBucket: 'abhimanyu-herbal-juice-6fa8e.firebasestorage.app',
  );

}